import type { Catalogue, Theme } from "./types";

export const mockCatalogues: Catalogue[] = [
  {
    id: "letters-and-words",
    name: "Letters & Words",
    description: "Build a practical foundation with everyday vocabulary and clear word recognition.",
    visual: "Aa",
    order: 1,
  },
  {
    id: "phrases-and-sentences",
    name: "Phrases & Sentences",
    description: "Connect the words you know into useful phrases and complete sentences.",
    visual: "Aa.",
    order: 2,
  },
  {
    id: "conversations",
    name: "Conversations",
    description: "Put your language skills into natural situations and everyday conversations.",
    visual: "…",
    order: 3,
  },
];

export const mockThemes: Theme[] = [
  {
    id: "everyday-animals",
    catalogueId: "letters-and-words",
    name: "Everyday Animals",
    description: "Learn common animal names and build a useful first vocabulary set.",
    visual: "🐾",
    order: 1,
    progress: 60,
    availability: "available",
  },
  {
    id: "food-and-drinks",
    catalogueId: "letters-and-words",
    name: "Food & Drinks",
    description: "Build vocabulary for meals, drinks, ingredients, and everyday choices.",
    visual: "🍎",
    order: 2,
    progress: 20,
    availability: "available",
  },
  {
    id: "daily-life",
    catalogueId: "letters-and-words",
    name: "Daily Life",
    description: "Learn practical words for routines, places, objects, and daily activities.",
    visual: "☀️",
    order: 3,
    progress: 0,
    availability: "locked",
  },
  {
    id: "daily-routines",
    catalogueId: "phrases-and-sentences",
    name: "Daily Routines",
    description: "Turn familiar vocabulary into phrases about routines and habits.",
    visual: "🕘",
    order: 1,
    progress: 35,
    availability: "available",
  },
  {
    id: "at-the-restaurant",
    catalogueId: "phrases-and-sentences",
    name: "At the Restaurant",
    description: "Practice useful phrases for ordering food and handling simple requests.",
    visual: "🍽️",
    order: 2,
    progress: 0,
    availability: "available",
  },
  {
    id: "making-plans",
    catalogueId: "phrases-and-sentences",
    name: "Making Plans",
    description: "Combine phrases to talk about plans, times, and simple arrangements.",
    visual: "📅",
    order: 3,
    progress: 0,
    availability: "locked",
  },
  {
    id: "introductions",
    catalogueId: "conversations",
    name: "Introductions",
    description: "Practice simple conversational patterns for meeting someone new.",
    visual: "👋",
    order: 1,
    progress: 0,
    availability: "available",
  },
  {
    id: "shopping",
    catalogueId: "conversations",
    name: "Shopping",
    description: "Use practical conversation patterns for prices, choices, and simple questions.",
    visual: "🛍️",
    order: 2,
    progress: 0,
    availability: "locked",
  },
  {
    id: "travel",
    catalogueId: "conversations",
    name: "Travel",
    description: "Build conversation confidence for common travel situations.",
    visual: "🧳",
    order: 3,
    progress: 0,
    availability: "locked",
  },
];
