import type { Exercise, ExerciseAttempt } from "./types";

export const mockExercises: Exercise[] = [
  {
    id: "animal-names-recognition",
    lessonId: "animal-names",
    order: 1,
    status: "published",
    title: "Recognize the animal",
    type: "recognition",
  },
  {
    id: "animal-names-spelling",
    lessonId: "animal-names",
    order: 2,
    status: "published",
    title: "Spell the animal name",
    type: "spelling",
  },
  {
    id: "animal-sounds-choice",
    lessonId: "animal-sounds",
    order: 1,
    status: "published",
    title: "Match the sound to the animal",
    type: "multiple_choice",
  },
  {
    id: "describing-animals-manipulation",
    lessonId: "describing-animals",
    order: 1,
    status: "published",
    title: "Build an animal description",
    type: "direct_manipulation",
  },
  {
    id: "wild-animals-recognition",
    lessonId: "wild-animals",
    order: 1,
    status: "published",
    title: "Identify the wild animal",
    type: "recognition",
  },
  {
    id: "food-basics-recognition",
    lessonId: "food-basics",
    order: 1,
    status: "published",
    title: "Recognize everyday foods",
    type: "recognition",
  },
  {
    id: "drinks-choice",
    lessonId: "drinks",
    order: 1,
    status: "published",
    title: "Choose the right drink",
    type: "multiple_choice",
  },
  {
    id: "daily-activities-choice",
    lessonId: "daily-activities",
    order: 1,
    status: "published",
    title: "Choose the daily activity",
    type: "multiple_choice",
  },
  {
    id: "talking-about-routines-spelling",
    lessonId: "talking-about-routines",
    order: 1,
    status: "published",
    title: "Build a routine phrase",
    type: "spelling",
  },
  {
    id: "ordering-food-manipulation",
    lessonId: "ordering-food",
    order: 1,
    status: "published",
    title: "Build an order",
    type: "direct_manipulation",
  },
  {
    id: "meeting-people-choice",
    lessonId: "meeting-people",
    order: 1,
    status: "published",
    title: "Choose the right introduction",
    type: "multiple_choice",
  },
];

export const mockExerciseAttempts: ExerciseAttempt[] = [
  {
    completedAt: "2026-09-25T10:15:00.000Z",
    exerciseId: "animal-names-recognition",
    id: "attempt-1",
    learnerId: "learner-1",
    score: 92,
    startedAt: "2026-09-25T10:10:00.000Z",
    status: "completed",
  },
  {
    completedAt: "2026-09-25T10:25:00.000Z",
    exerciseId: "animal-names-spelling",
    id: "attempt-2",
    learnerId: "learner-1",
    score: 100,
    startedAt: "2026-09-25T10:20:00.000Z",
    status: "completed",
  },
  {
    exerciseId: "animal-sounds-choice",
    id: "attempt-3",
    learnerId: "learner-1",
    score: 78,
    startedAt: "2026-09-26T09:00:00.000Z",
    status: "in_progress",
  },
];
